insert into books (author_id, title, priceOld, price) values (1,'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author_id, title, priceOld, price) values (2, 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author_id, title, priceOld, price) values (3, 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author_id, title, priceOld, price) values (4, 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author_id, title, priceOld, price) values (5, 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author_id, title, priceOld, price) values (6, 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author_id, title, priceOld, price) values (7, 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author_id, title, priceOld, price) values (8, 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author_id, title, priceOld, price) values (9, 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author_id, title, priceOld, price) values (10, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author_id, title, priceOld, price) values (11, 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author_id, title, priceOld, price) values (12, 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author_id, title, priceOld, price) values (13, 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author_id, title, priceOld, price) values (14, 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author_id, title, priceOld, price) values (15, 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author_id, title, priceOld, price) values (16, 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author_id, title, priceOld, price) values (17, 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author_id, title, priceOld, price) values (18, 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author_id, title, priceOld, price) values (19, 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author_id, title, priceOld, price) values (20, 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author_id, title, priceOld, price) values (21, 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author_id, title, priceOld, price) values (20, 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author_id, title, priceOld, price) values (22, 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author_id, title, priceOld, price) values (23, 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author_id, title, priceOld, price) values (24, 'facilitate efficient eyeballs', '$232.30', '$131.48');

insert into authors (id,fio,biography) VALUES (1,'Drucie Goodbourn','Drucie Goodbourn biography');
insert into authors (id,fio,biography) VALUES (2,'Marcia Aggiss','Marcia Aggiss biography');
insert into authors (id,fio,biography) VALUES (3,'Giovanni Bigg','Giovanni Bigg biography');
insert into authors (id,fio,biography) VALUES (4,'Duffie Eynon','Duffie Eynon biography');
insert into authors (id,fio,biography) VALUES (5,'Anselma McKennan','Anselma McKennan biography');
insert into authors (id,fio,biography) VALUES (6,'Gert Kira','Gert Kira biography');
insert into authors (id,fio,biography) VALUES (7,'Clerc Djakovic','Clerc Djakovic biography');
insert into authors (id,fio,biography) VALUES (8,'Stacee Elsy','Stacee Elsy biography');
insert into authors (id,fio,biography) VALUES (9,'Dorotea Bonhill','Dorotea Bonhill biography');
insert into authors (id,fio,biography) VALUES (10,'Minni Bunney','Minni Bunney biography');
insert into authors (id,fio,biography) VALUES (11,'Berty Gandley','Berty Gandley biography');
insert into authors (id,fio,biography) VALUES (12,'Raynard Tesdale','Raynard Tesdale biography');
insert into authors (id,fio,biography) VALUES (13,'Joanna Hutfield','Joanna Hutfield biography');
insert into authors (id,fio,biography) VALUES (14,'Dannie Glidder','Dannie Glidder biography');
insert into authors (id,fio,biography) VALUES (15,'Timmie Adshede','Timmie Adshede biography');
insert into authors (id,fio,biography) VALUES (16,'Fernando Neads','Fernando Neads biography');
insert into authors (id,fio,biography) VALUES (17,'Teddy Guilliland','Teddy Guilliland biography');
insert into authors (id,fio,biography) VALUES (18,'Paloma Grebert','Paloma Grebert biography');
insert into authors (id,fio,biography) VALUES (19,'Kristos Usher','Kristos Usher biography');
insert into authors (id,fio,biography) VALUES (20,'Lindsay Coutthart','Lindsay Coutthart biography');
insert into authors (id,fio,biography) VALUES (21,'Cristie Isacsson','Cristie Isacsson biography');
insert into authors (id,fio,biography) VALUES (22,'Helyn Schneidar','Helyn Schneidar biography');
insert into authors (id,fio,biography) VALUES (23,'Bette-ann Askem','Bette-ann Askem biography');
insert into authors (id,fio,biography) VALUES (24,'Dom Robuchon','Dom Robuchon biography');