insert into tag (id, name) values (1, 'Pine View');
insert into tag (id, name) values (2, 'Hintze');
insert into tag (id, name) values (3, 'Hagan');
insert into tag (id, name) values (4, 'Hintze2');
insert into tag (id, name) values (5, 'Ramsey');
insert into tag (id, name) values (6, 'Raven');
insert into tag (id, name) values (7, 'Mallory');
insert into tag (id, name) values (8, 'Rigney');
insert into tag (id, name) values (9, 'David');
insert into tag (id, name) values (10, 'Hallows');
insert into tag (id, name) values (11, 'Bay');
insert into tag (id, name) values (12, 'Ronald Regan');
insert into tag (id, name) values (13, 'Mifflin');
insert into tag (id, name) values (14, 'Barnett');
insert into tag (id, name) values (15, 'Havey');
insert into tag (id, name) values (16, 'Lake View');
insert into tag (id, name) values (17, 'Mayer');
insert into tag (id, name) values (18, 'Summit');
insert into tag (id, name) values (19, 'Superior');
insert into tag (id, name) values (20, 'Pierstorff');
insert into tag (id, name) values (21, 'Dorton');
insert into tag (id, name) values (22, 'Main');
insert into tag (id, name) values (23, 'Logan');
insert into tag (id, name) values (24, 'Brickson Park');
insert into tag (id, name) values (25, 'Hoffman');
insert into tag (id, name) values (26, 'Sheridan');
insert into tag (id, name) values (27, 'Mariners Cove');
insert into tag (id, name) values (28, 'Maywood');
insert into tag (id, name) values (29, 'Ryan');
insert into tag (id, name) values (30, 'Ridgeway');
insert into tag (id, name) values (31, 'Moland');
insert into tag (id, name) values (32, 'Welch');
insert into tag (id, name) values (33, '4th');
insert into tag (id, name) values (34, 'Eagan');
insert into tag (id, name) values (35, 'Onsgard');
insert into tag (id, name) values (36, 'Derek');
insert into tag (id, name) values (37, 'Vermont');
insert into tag (id, name) values (38, 'Morrow');
insert into tag (id, name) values (39, 'Darwin');
insert into tag (id, name) values (40, 'Eliot');
insert into tag (id, name) values (41, 'Hauk');
insert into tag (id, name) values (42, 'Warbler');
insert into tag (id, name) values (43, 'Jay');
insert into tag (id, name) values (44, 'Cordelia');
insert into tag (id, name) values (45, 'Springs');
insert into tag (id, name) values (46, 'Mitchell');
insert into tag (id, name) values (47, 'Troy');
insert into tag (id, name) values (48, 'Dwight');
insert into tag (id, name) values (49, 'Melrose');
insert into tag (id, name) values (50, 'Rieder');