insert into book_review (id, book_id, user_id, time, text) values (1, 8, 45, '2021-06-03', 'Fluoroscopy of Single Coronary Artery Bypass Graft using Other Contrast, Laser Intraoperative');
insert into book_review (id, book_id, user_id, time, text) values (2, 40, 45, '2020-11-13', 'Replacement of Right Upper Eyelid with Autologous Tissue Substitute, Percutaneous Approach');
insert into book_review (id, book_id, user_id, time, text) values (3, 40, 18, '2020-12-22', 'Insertion of Endobronchial Valve into Lingula Bronchus, Percutaneous Approach');
insert into book_review (id, book_id, user_id, time, text) values (4, 29, 14, '2021-05-31', 'Revision of Spacer in Cervical Vertebral Joint, External Approach');
insert into book_review (id, book_id, user_id, time, text) values (5, 44, 35, '2021-01-25', 'Resection of Bilateral Spermatic Cords, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (6, 30, 50, '2020-10-02', 'Excision of Stomach, Percutaneous Approach, Diagnostic');
insert into book_review (id, book_id, user_id, time, text) values (7, 7, 22, '2021-06-27', 'Excision of Left Fallopian Tube, Percutaneous Endoscopic Approach, Diagnostic');
insert into book_review (id, book_id, user_id, time, text) values (8, 12, 32, '2020-08-17', 'Ear Protector Attentuation Assessment');
insert into book_review (id, book_id, user_id, time, text) values (9, 30, 23, '2020-07-10', 'Destruction of Right Ethmoid Bone, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (10, 36, 9, '2020-11-19', 'Extirpation of Matter from Intracranial Vein, Percutaneous Approach');
insert into book_review (id, book_id, user_id, time, text) values (11, 12, 37, '2020-08-13', 'Control Bleeding in Oral Cavity and Throat, Via Natural or Artificial Opening');
insert into book_review (id, book_id, user_id, time, text) values (12, 20, 4, '2020-07-08', 'Dilation of Gastric Vein, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (13, 18, 28, '2021-03-29', 'Removal of Nonautologous Tissue Substitute from Right Lower Femur, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (14, 19, 39, '2021-03-01', 'Dilation of Gastric Artery, Bifurcation, with Intraluminal Device, Percutaneous Approach');
insert into book_review (id, book_id, user_id, time, text) values (15, 46, 1, '2020-07-12', 'Excision of Left Atrial Appendage, Percutaneous Approach');
insert into book_review (id, book_id, user_id, time, text) values (16, 28, 21, '2020-10-11', 'Dilation of Left Internal Iliac Artery with Three Drug-eluting Intraluminal Devices, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (17, 28, 46, '2021-02-20', 'Dilation of Left Internal Mammary Artery with Four or More Drug-eluting Intraluminal Devices, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (18, 7, 27, '2020-12-01', 'Insertion of External Fixation Device into Left Humeral Shaft, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (19, 24, 49, '2021-01-17', 'Bypass Left Cephalic Vein to Upper Vein with Synthetic Substitute, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (20, 43, 32, '2020-07-09', 'Drainage of Cerebral Meninges, Percutaneous Approach, Diagnostic');
insert into book_review (id, book_id, user_id, time, text) values (21, 47, 16, '2020-12-31', 'Insertion of Neurostimulator Lead into Spinal Cord, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (22, 11, 6, '2020-10-19', 'Insertion of Defibrillator Lead into Pericardium, Percutaneous Approach');
insert into book_review (id, book_id, user_id, time, text) values (23, 8, 21, '2021-05-07', 'Fusion of Cervical Vertebral Joint with Interbody Fusion Device, Posterior Approach, Posterior Column, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (24, 29, 9, '2020-11-20', 'Excision of Left Orbit, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (25, 23, 49, '2020-09-08', 'Drainage of Bilateral Breast with Drainage Device, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (26, 12, 6, '2020-10-22', 'Division of Cervical Nerve, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (27, 19, 30, '2020-09-23', 'Supplement Left Frontal Bone with Nonautologous Tissue Substitute, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (28, 1, 31, '2021-02-10', 'Dilation of Face Artery with Three Drug-eluting Intraluminal Devices, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (29, 6, 39, '2020-11-14', 'Excision of Right Thorax Tendon, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (30, 35, 6, '2021-05-13', 'Revision of Synthetic Substitute in Right Tympanic Membrane, Via Natural or Artificial Opening');
insert into book_review (id, book_id, user_id, time, text) values (31, 29, 15, '2021-01-25', 'Excision of Left Brachial Vein, Percutaneous Approach, Diagnostic');
insert into book_review (id, book_id, user_id, time, text) values (32, 21, 32, '2021-04-13', 'Repair Uterus, Via Natural or Artificial Opening Endoscopic');
insert into book_review (id, book_id, user_id, time, text) values (33, 37, 9, '2021-04-29', 'Drainage of Left Diaphragm, Percutaneous Endoscopic Approach, Diagnostic');
insert into book_review (id, book_id, user_id, time, text) values (34, 21, 14, '2020-11-21', 'Replacement of Right Popliteal Artery with Nonautologous Tissue Substitute, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (35, 12, 11, '2021-04-16', 'Supplement Ulnar Nerve with Autologous Tissue Substitute, Percutaneous Approach');
insert into book_review (id, book_id, user_id, time, text) values (36, 48, 48, '2020-10-11', 'Destruction of Lumbar Sympathetic Nerve, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (37, 34, 49, '2020-10-24', 'Replacement of Left Pulmonary Artery with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (38, 14, 11, '2020-08-11', 'Bypass Gallbladder to Caudate Hepatic Duct with Intraluminal Device, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (39, 17, 36, '2021-04-29', 'Therapeutic Exercise Treatment of Musculoskeletal System - Lower Back / Lower Extremity using Orthosis');
insert into book_review (id, book_id, user_id, time, text) values (40, 47, 8, '2021-05-27', 'Division of Right Upper Arm Muscle, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (41, 4, 50, '2021-02-18', 'Restriction of Large Intestine, Via Natural or Artificial Opening Endoscopic');
insert into book_review (id, book_id, user_id, time, text) values (42, 47, 41, '2021-01-26', 'Bypass Thoracic Aorta, Ascending/Arch to Subclavian with Nonautologous Tissue Substitute, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (43, 48, 39, '2020-07-04', 'Insertion of Intraluminal Device into Left Vertebral Vein, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (44, 41, 49, '2021-01-22', 'Removal of Drainage Device from Larynx, External Approach');
insert into book_review (id, book_id, user_id, time, text) values (45, 5, 8, '2020-12-10', 'Bypass Right Atrium to Left Pulmonary Artery with Autologous Venous Tissue, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (46, 19, 37, '2020-09-11', 'Replacement of Larynx with Nonautologous Tissue Substitute, Via Natural or Artificial Opening');
insert into book_review (id, book_id, user_id, time, text) values (47, 45, 13, '2020-12-19', 'Reposition Right Humeral Shaft, Percutaneous Endoscopic Approach');
insert into book_review (id, book_id, user_id, time, text) values (48, 46, 44, '2020-10-28', 'Supplement Atrial Septum with Synthetic Substitute, Open Approach');
insert into book_review (id, book_id, user_id, time, text) values (49, 39, 8, '2020-11-24', 'Removal of Extraluminal Device from Kidney, Via Natural or Artificial Opening Endoscopic');
insert into book_review (id, book_id, user_id, time, text) values (50, 21, 19, '2021-01-21', 'Repair Right Lower Arm Skin, External Approach');
