insert into genre (id, parent_id, slug, name) values (1, null, 'rifampin', 'rifampin');
insert into genre (id, parent_id, slug, name) values (2, null, 'Garnier Fructis Antidandruff', 'Pyrithione Zinc');
insert into genre (id, parent_id, slug, name) values (3, null, 'ULTRASOL', 'Titanium Dioxide, Zinc Oxide');
insert into genre (id, parent_id, slug, name) values (4, null, 'Propafenone Hydrochloride', 'Propafenone Hydrochloride');
insert into genre (id, parent_id, slug, name) values (5, null, 'Anticavity Fluoride Rinse', 'Sodium Fluoride');
insert into genre (id, parent_id, slug, name) values (6, null, 'TOPIRAMATE', 'TOPIRAMATE');
insert into genre (id, parent_id, slug, name) values (7, null, 'Pleo Sancom', 'mucor racemosus and aspergillus niger var. niger');
insert into genre (id, parent_id, slug, name) values (8, null, 'BACTROBAN', 'mupirocin calcium');
insert into genre (id, parent_id, slug, name) values (9, null, 'Maximum Strength Zantac', 'ranitidine');
insert into genre (id, parent_id, slug, name) values (10, null, 'Treatment Set TS348405', 'Treatment Set TS348405');
insert into genre (id, parent_id, slug, name) values (11, null, 'Deep Renewal', 'Avobenzone, Octinoxate, Octocrylene, Oxybenzone, and Dimethicone');
insert into genre (id, parent_id, slug, name) values (12, null, 'Softlips Sugar Plum Berry', 'Dimethicone, Octinoxate, Octisalate, Oxybenzone');
insert into genre (id, parent_id, slug, name) values (13, null, 'Herpeset', 'Apis mellifica, Arsenicum album, Baptisia tinctoria, Capsicum annuum, Dulcamara, Echinacea, Nitricum acidum, Pyrogenium, Rhus toxicodendron,');
insert into genre (id, parent_id, slug, name) values (14, null, 'MEDI-FIRST Non-Aspirin', 'Acetaminophen');
insert into genre (id, parent_id, slug, name) values (15, null, 'Smart Sense ibuprofen', 'Ibuprofen');
insert into genre (id, parent_id, slug, name) values (16, null, 'Guaifenesin', 'Guaifenesin');
insert into genre (id, parent_id, slug, name) values (17, null, 'Nicardipine HCl', 'Nicardipine HCl');
insert into genre (id, parent_id, slug, name) values (18, null, 'Olay Total Effects Pore Minimizing CC', 'Homosalate, Octisalate, and Octocrylene');
insert into genre (id, parent_id, slug, name) values (19, null, 'Ibuprofen', 'Ibuprofen');
insert into genre (id, parent_id, slug, name) values (20, null, 'JUGLANS NIGRA POLLEN', 'California Walnut Black Pollen');

insert into genre (id, parent_id, slug, name) values (21, 1, 'JUGLANS NIGRA POLLEN (child1)', 'California Walnut Black Pollen (child)1');
insert into genre (id, parent_id, slug, name) values (22, 21, 'JUGLANS NIGRA POLLEN (child (child)1)', 'California Walnut Black Pollen (child)2');
insert into genre (id, parent_id, slug, name) values (23, 2, 'JUGLANS NIGRA POLLEN (child2)', 'California Walnut Black Pollen (child)3');
insert into genre (id, parent_id, slug, name) values (24, 1, 'JUGLANS NIGRA POLLEN (child3)', 'California Walnut Black Pollen (child)4');